<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.frailty9</groupId>
        <artifactId>framegen</artifactId>
        <version>0.2.2</version>
    </parent>

    <artifactId>framegen-solon-plugin</artifactId>

    <name>FrameGen Solon Plugin</name>
    <description>Integration of FrameGen with Solon framework</description>
    <url>https://gitee.com/frailty/frame-gen/tree/main/framegen-solon-plugin</url>

    <licenses>
        <license>
            <name>The MIT License</name>
            <url>http://opensource.org/licenses/MIT</url>
        </license>
    </licenses>
    
    <scm>
        <connection>scm:git:https://gitee.com/frailty/frame-gen.git</connection>
        <developerConnection>scm:git:git@gitee.com:frailty/frame-gen.git</developerConnection>
        <url>https://gitee.com/frailty/frame-gen</url>
    </scm>

    <developers>
        <developer>
            <id>Frailty</id>
            <name>花殇</name>
            <email>ydl9263@qq.com</email>
        </developer>
    </developers>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.github.frailty9</groupId>
            <artifactId>framegen-core</artifactId>
            <version>0.2.2</version>
            <exclusions>
                <exclusion>
                    <groupId>com.zaxxer</groupId>
                    <artifactId>HikariCP</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.noear</groupId>
            <artifactId>solon</artifactId>
            <version>2.9.1</version>
            <optional>true</optional>
        </dependency>
    </dependencies>

</project>